### ISSUE TITLE
Idk what title to put

### ISSUE THREAD

**Issue by NotDemonix** [evinism/oceanic#1]
Hello, some time ago guy named DonovanDMC started making discord api framework and he called it oceanic, we would like to ask you if it would be possible for you to give us oceanic name on npm

**Comment by NotDemonix** [comment]
We set name to oceanic.js

**Comment by evinism** [comment]
mmk, ty ty. Not opposed to giving you this name, but i've been really really busy so haven't had time to address it. I'd love to see your project! Link it?
